### ISSUE TITLE
status of this project

### ISSUE THREAD

**Issue by martinjrobins** [rwl/suitesparse_sys#1]
Hi, I have developed a `suitesparse-sys` crate [here](https://github.com/martinjrobins/suitesparse-sys) and I'm interested in publishing to crates.io, but the name has been taken by this project. I can see this hasn't been updated in a while, so wanted to check on the status of the project, do you plan to continue developing this?

**Comment by rwl** [comment]
I can probably just use your version for [spsolve](https://crates.io/crates/spsolve) int the future. One issue might be that I had to override some of the generated KLU signatures due to issues with the mut/const:

https://github.com/rwl/suitesparse_sys/blob/main/src/lib.rs#L23-L51

I can add you as an owner on [crates.io](https://crates.io/crates/suitesparse_sys/settings). Is your username "martinjrobins"?

**Comment by martinjrobins** [comment]
Yup, that is me, thanks! I’ll make sure I fix those signatures before I publish

**Comment by martinjrobins** [comment]
I've now published v0.1.1 of the crate and fixed those signatures. Let me know if this works for you in `spsolve`

**Comment by rwl** [comment]
It would be helpful if the new bindings had the modified KLU function definitions, but for the `klu_z_` and `klu_zl_` complex variants of the functions too.

**Comment by martinjrobins** [comment]
yea, happy to add these as well
